_opret_advisering = """{
  "adviseringsType": {},
  "sagReference": {},
  "ansvar": {},
  "ydelseId": null,
  "titel": "",
  "beskrivelse": "",
  "modtager": {}
}"""

_opret_aktivitet = """{
  "aktindsigt": true,
  "laast": false,
  "lovpligtig": false,
  "sekundaerBehandler": [],
  "inddragelseInddragelser": [],
  "inddragelseInddragelsesFormer": [],
  "udeladtSamtale": false,
  "baggrundeForUnderretningBarnet": [],
  "baggrundeForUnderretningHjemmet": [],
  "baggrundeForUnderretningAndet": [],
  "recovery": false,
  "afgoerelseEfter": {},
  "status": null,
  "sagReference": null,
  "undersoegelsenGennemfoertEfter": {},
  "grundlagForUndersoegelsen": {},
  "samtykke": {},
  "medSamtykkeLbu": {},
  "udenSamtykkeLbu": {},
  "lovgrundlag": {},
  "opretKalenderinvitation": false,
  "aktivitetBemaerkning": {},
  "boernesamtalerForAktivitet": [],
  "prioritet": null,
  "primaerBehandlerNavn": null,
  "primaerBehandlerId": null,
  "vedroerer": null,
  "type": null,
  "undertype": null,
  "haendelsesDato": null,
  "notat": "",
  "beskrivelse": ""
}"""